/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as DarmtherapieTrajectRouteImport } from './routes/darmtherapie-traject'
import { Route as LinktreeRouteImport } from './routes/linktree'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutBehandelingenRouteImport } from './routes/_layout/behandelingen'
import { Route as LayoutBloedsuikertrajectRouteImport } from './routes/_layout/bloedsuikertraject'
import { Route as LayoutContactRouteImport } from './routes/_layout/contact'
import { Route as LayoutCookiePolicyRouteImport } from './routes/_layout/cookie-policy'
import { Route as LayoutDarmtrajectRouteImport } from './routes/_layout/darmtraject'
import { Route as LayoutEBookRouteImport } from './routes/_layout/e-book'
import { Route as LayoutEBookBoodschappenlijstRouteImport } from './routes/_layout/e-book-boodschappenlijst'
import { Route as LayoutEBookMealprepSnacksRouteImport } from './routes/_layout/e-book-mealprep-snacks'
import { Route as LayoutEBookReceptenSnacksRouteImport } from './routes/_layout/e-book-recepten-snacks'
import { Route as LayoutEBookWeekmenuRouteImport } from './routes/_layout/e-book-weekmenu'
import { Route as LayoutFaqRouteImport } from './routes/_layout/faq'
import { Route as LayoutGlowupRouteImport } from './routes/_layout/glowup'
import { Route as LayoutHormoontrajectRouteImport } from './routes/_layout/hormoontraject'
import { Route as LayoutMethodRouteImport } from './routes/_layout/method'
import { Route as LayoutNieuwsbriefRouteImport } from './routes/_layout/nieuwsbrief'
import { Route as LayoutOverMijRouteImport } from './routes/_layout/over-mij'
import { Route as LayoutPodcastRouteImport } from './routes/_layout/podcast'
import { Route as LayoutPrivacyRouteImport } from './routes/_layout/privacy'
import { Route as LayoutTermsRouteImport } from './routes/_layout/terms'
import { Route as LayoutBlogIndexRouteImport } from './routes/_layout/blog/index'
import { Route as LayoutBlogSlugRouteImport } from './routes/_layout/blog/$slug'
import { Route as LayoutReceptenIndexRouteImport } from './routes/_layout/recepten/index'
import { Route as LayoutReceptenSlugRouteImport } from './routes/_layout/recepten/$slug'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DarmtherapieTrajectRoute = DarmtherapieTrajectRouteImport.update({
  id: '/darmtherapie-traject',
  path: '/darmtherapie-traject',
  getParentRoute: () => rootRouteImport,
} as any)
const LinktreeRoute = LinktreeRouteImport.update({
  id: '/linktree',
  path: '/linktree',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBehandelingenRoute = LayoutBehandelingenRouteImport.update({
  id: '/behandelingen',
  path: '/behandelingen',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBloedsuikertrajectRoute =
  LayoutBloedsuikertrajectRouteImport.update({
    id: '/bloedsuikertraject',
    path: '/bloedsuikertraject',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutContactRoute = LayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCookiePolicyRoute = LayoutCookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDarmtrajectRoute = LayoutDarmtrajectRouteImport.update({
  id: '/darmtraject',
  path: '/darmtraject',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEBookRoute = LayoutEBookRouteImport.update({
  id: '/e-book',
  path: '/e-book',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEBookBoodschappenlijstRoute =
  LayoutEBookBoodschappenlijstRouteImport.update({
    id: '/e-book-boodschappenlijst',
    path: '/e-book-boodschappenlijst',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutEBookMealprepSnacksRoute =
  LayoutEBookMealprepSnacksRouteImport.update({
    id: '/e-book-mealprep-snacks',
    path: '/e-book-mealprep-snacks',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutEBookReceptenSnacksRoute =
  LayoutEBookReceptenSnacksRouteImport.update({
    id: '/e-book-recepten-snacks',
    path: '/e-book-recepten-snacks',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutEBookWeekmenuRoute = LayoutEBookWeekmenuRouteImport.update({
  id: '/e-book-weekmenu',
  path: '/e-book-weekmenu',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFaqRoute = LayoutFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGlowupRoute = LayoutGlowupRouteImport.update({
  id: '/glowup',
  path: '/glowup',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHormoontrajectRoute = LayoutHormoontrajectRouteImport.update({
  id: '/hormoontraject',
  path: '/hormoontraject',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMethodRoute = LayoutMethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNieuwsbriefRoute = LayoutNieuwsbriefRouteImport.update({
  id: '/nieuwsbrief',
  path: '/nieuwsbrief',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOverMijRoute = LayoutOverMijRouteImport.update({
  id: '/over-mij',
  path: '/over-mij',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPodcastRoute = LayoutPodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPrivacyRoute = LayoutPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTermsRoute = LayoutTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlogIndexRoute = LayoutBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlogSlugRoute = LayoutBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReceptenIndexRoute = LayoutReceptenIndexRouteImport.update({
  id: '/recepten/',
  path: '/recepten/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReceptenSlugRoute = LayoutReceptenSlugRouteImport.update({
  id: '/recepten/$slug',
  path: '/recepten/$slug',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/darmtherapie-traject': typeof DarmtherapieTrajectRoute
  '/linktree': typeof LinktreeRoute
  '/behandelingen': typeof LayoutBehandelingenRoute
  '/bloedsuikertraject': typeof LayoutBloedsuikertrajectRoute
  '/contact': typeof LayoutContactRoute
  '/cookie-policy': typeof LayoutCookiePolicyRoute
  '/darmtraject': typeof LayoutDarmtrajectRoute
  '/e-book': typeof LayoutEBookRoute
  '/e-book-boodschappenlijst': typeof LayoutEBookBoodschappenlijstRoute
  '/e-book-mealprep-snacks': typeof LayoutEBookMealprepSnacksRoute
  '/e-book-recepten-snacks': typeof LayoutEBookReceptenSnacksRoute
  '/e-book-weekmenu': typeof LayoutEBookWeekmenuRoute
  '/faq': typeof LayoutFaqRoute
  '/glowup': typeof LayoutGlowupRoute
  '/hormoontraject': typeof LayoutHormoontrajectRoute
  '/method': typeof LayoutMethodRoute
  '/nieuwsbrief': typeof LayoutNieuwsbriefRoute
  '/over-mij': typeof LayoutOverMijRoute
  '/podcast': typeof LayoutPodcastRoute
  '/privacy': typeof LayoutPrivacyRoute
  '/terms': typeof LayoutTermsRoute
  '/blog/$slug': typeof LayoutBlogSlugRoute
  '/recepten/$slug': typeof LayoutReceptenSlugRoute
  '/blog/': typeof LayoutBlogIndexRoute
  '/recepten/': typeof LayoutReceptenIndexRoute
}
export interface FileRoutesByTo {
  '/darmtherapie-traject': typeof DarmtherapieTrajectRoute
  '/linktree': typeof LinktreeRoute
  '/behandelingen': typeof LayoutBehandelingenRoute
  '/bloedsuikertraject': typeof LayoutBloedsuikertrajectRoute
  '/contact': typeof LayoutContactRoute
  '/cookie-policy': typeof LayoutCookiePolicyRoute
  '/darmtraject': typeof LayoutDarmtrajectRoute
  '/e-book': typeof LayoutEBookRoute
  '/e-book-boodschappenlijst': typeof LayoutEBookBoodschappenlijstRoute
  '/e-book-mealprep-snacks': typeof LayoutEBookMealprepSnacksRoute
  '/e-book-recepten-snacks': typeof LayoutEBookReceptenSnacksRoute
  '/e-book-weekmenu': typeof LayoutEBookWeekmenuRoute
  '/faq': typeof LayoutFaqRoute
  '/glowup': typeof LayoutGlowupRoute
  '/hormoontraject': typeof LayoutHormoontrajectRoute
  '/method': typeof LayoutMethodRoute
  '/nieuwsbrief': typeof LayoutNieuwsbriefRoute
  '/over-mij': typeof LayoutOverMijRoute
  '/podcast': typeof LayoutPodcastRoute
  '/privacy': typeof LayoutPrivacyRoute
  '/terms': typeof LayoutTermsRoute
  '/': typeof LayoutIndexRoute
  '/blog/$slug': typeof LayoutBlogSlugRoute
  '/recepten/$slug': typeof LayoutReceptenSlugRoute
  '/blog': typeof LayoutBlogIndexRoute
  '/recepten': typeof LayoutReceptenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/darmtherapie-traject': typeof DarmtherapieTrajectRoute
  '/linktree': typeof LinktreeRoute
  '/_layout/behandelingen': typeof LayoutBehandelingenRoute
  '/_layout/bloedsuikertraject': typeof LayoutBloedsuikertrajectRoute
  '/_layout/contact': typeof LayoutContactRoute
  '/_layout/cookie-policy': typeof LayoutCookiePolicyRoute
  '/_layout/darmtraject': typeof LayoutDarmtrajectRoute
  '/_layout/e-book': typeof LayoutEBookRoute
  '/_layout/e-book-boodschappenlijst': typeof LayoutEBookBoodschappenlijstRoute
  '/_layout/e-book-mealprep-snacks': typeof LayoutEBookMealprepSnacksRoute
  '/_layout/e-book-recepten-snacks': typeof LayoutEBookReceptenSnacksRoute
  '/_layout/e-book-weekmenu': typeof LayoutEBookWeekmenuRoute
  '/_layout/faq': typeof LayoutFaqRoute
  '/_layout/glowup': typeof LayoutGlowupRoute
  '/_layout/hormoontraject': typeof LayoutHormoontrajectRoute
  '/_layout/method': typeof LayoutMethodRoute
  '/_layout/nieuwsbrief': typeof LayoutNieuwsbriefRoute
  '/_layout/over-mij': typeof LayoutOverMijRoute
  '/_layout/podcast': typeof LayoutPodcastRoute
  '/_layout/privacy': typeof LayoutPrivacyRoute
  '/_layout/terms': typeof LayoutTermsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/blog/$slug': typeof LayoutBlogSlugRoute
  '/_layout/recepten/$slug': typeof LayoutReceptenSlugRoute
  '/_layout/blog/': typeof LayoutBlogIndexRoute
  '/_layout/recepten/': typeof LayoutReceptenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/darmtherapie-traject'
    | '/linktree'
    | '/behandelingen'
    | '/bloedsuikertraject'
    | '/contact'
    | '/cookie-policy'
    | '/darmtraject'
    | '/e-book'
    | '/e-book-boodschappenlijst'
    | '/e-book-mealprep-snacks'
    | '/e-book-recepten-snacks'
    | '/e-book-weekmenu'
    | '/faq'
    | '/glowup'
    | '/hormoontraject'
    | '/method'
    | '/nieuwsbrief'
    | '/over-mij'
    | '/podcast'
    | '/privacy'
    | '/terms'
    | '/blog/$slug'
    | '/recepten/$slug'
    | '/blog/'
    | '/recepten/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/darmtherapie-traject'
    | '/linktree'
    | '/behandelingen'
    | '/bloedsuikertraject'
    | '/contact'
    | '/cookie-policy'
    | '/darmtraject'
    | '/e-book'
    | '/e-book-boodschappenlijst'
    | '/e-book-mealprep-snacks'
    | '/e-book-recepten-snacks'
    | '/e-book-weekmenu'
    | '/faq'
    | '/glowup'
    | '/hormoontraject'
    | '/method'
    | '/nieuwsbrief'
    | '/over-mij'
    | '/podcast'
    | '/privacy'
    | '/terms'
    | '/'
    | '/blog/$slug'
    | '/recepten/$slug'
    | '/blog'
    | '/recepten'
  id:
    | '__root__'
    | '/_layout'
    | '/darmtherapie-traject'
    | '/linktree'
    | '/_layout/behandelingen'
    | '/_layout/bloedsuikertraject'
    | '/_layout/contact'
    | '/_layout/cookie-policy'
    | '/_layout/darmtraject'
    | '/_layout/e-book'
    | '/_layout/e-book-boodschappenlijst'
    | '/_layout/e-book-mealprep-snacks'
    | '/_layout/e-book-recepten-snacks'
    | '/_layout/e-book-weekmenu'
    | '/_layout/faq'
    | '/_layout/glowup'
    | '/_layout/hormoontraject'
    | '/_layout/method'
    | '/_layout/nieuwsbrief'
    | '/_layout/over-mij'
    | '/_layout/podcast'
    | '/_layout/privacy'
    | '/_layout/terms'
    | '/_layout/'
    | '/_layout/blog/$slug'
    | '/_layout/recepten/$slug'
    | '/_layout/blog/'
    | '/_layout/recepten/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  DarmtherapieTrajectRoute: typeof DarmtherapieTrajectRoute
  LinktreeRoute: typeof LinktreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darmtherapie-traject': {
      id: '/darmtherapie-traject'
      path: '/darmtherapie-traject'
      fullPath: '/darmtherapie-traject'
      preLoaderRoute: typeof DarmtherapieTrajectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linktree': {
      id: '/linktree'
      path: '/linktree'
      fullPath: '/linktree'
      preLoaderRoute: typeof LinktreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/behandelingen': {
      id: '/_layout/behandelingen'
      path: '/behandelingen'
      fullPath: '/behandelingen'
      preLoaderRoute: typeof LayoutBehandelingenRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/bloedsuikertraject': {
      id: '/_layout/bloedsuikertraject'
      path: '/bloedsuikertraject'
      fullPath: '/bloedsuikertraject'
      preLoaderRoute: typeof LayoutBloedsuikertrajectRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contact': {
      id: '/_layout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LayoutContactRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cookie-policy': {
      id: '/_layout/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof LayoutCookiePolicyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/darmtraject': {
      id: '/_layout/darmtraject'
      path: '/darmtraject'
      fullPath: '/darmtraject'
      preLoaderRoute: typeof LayoutDarmtrajectRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/e-book': {
      id: '/_layout/e-book'
      path: '/e-book'
      fullPath: '/e-book'
      preLoaderRoute: typeof LayoutEBookRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/e-book-boodschappenlijst': {
      id: '/_layout/e-book-boodschappenlijst'
      path: '/e-book-boodschappenlijst'
      fullPath: '/e-book-boodschappenlijst'
      preLoaderRoute: typeof LayoutEBookBoodschappenlijstRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/e-book-mealprep-snacks': {
      id: '/_layout/e-book-mealprep-snacks'
      path: '/e-book-mealprep-snacks'
      fullPath: '/e-book-mealprep-snacks'
      preLoaderRoute: typeof LayoutEBookMealprepSnacksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/e-book-recepten-snacks': {
      id: '/_layout/e-book-recepten-snacks'
      path: '/e-book-recepten-snacks'
      fullPath: '/e-book-recepten-snacks'
      preLoaderRoute: typeof LayoutEBookReceptenSnacksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/e-book-weekmenu': {
      id: '/_layout/e-book-weekmenu'
      path: '/e-book-weekmenu'
      fullPath: '/e-book-weekmenu'
      preLoaderRoute: typeof LayoutEBookWeekmenuRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/faq': {
      id: '/_layout/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof LayoutFaqRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/glowup': {
      id: '/_layout/glowup'
      path: '/glowup'
      fullPath: '/glowup'
      preLoaderRoute: typeof LayoutGlowupRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/hormoontraject': {
      id: '/_layout/hormoontraject'
      path: '/hormoontraject'
      fullPath: '/hormoontraject'
      preLoaderRoute: typeof LayoutHormoontrajectRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/method': {
      id: '/_layout/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof LayoutMethodRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/nieuwsbrief': {
      id: '/_layout/nieuwsbrief'
      path: '/nieuwsbrief'
      fullPath: '/nieuwsbrief'
      preLoaderRoute: typeof LayoutNieuwsbriefRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/over-mij': {
      id: '/_layout/over-mij'
      path: '/over-mij'
      fullPath: '/over-mij'
      preLoaderRoute: typeof LayoutOverMijRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/podcast': {
      id: '/_layout/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof LayoutPodcastRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/privacy': {
      id: '/_layout/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof LayoutPrivacyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/terms': {
      id: '/_layout/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LayoutTermsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/blog/': {
      id: '/_layout/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof LayoutBlogIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/blog/$slug': {
      id: '/_layout/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof LayoutBlogSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recepten/': {
      id: '/_layout/recepten/'
      path: '/recepten'
      fullPath: '/recepten/'
      preLoaderRoute: typeof LayoutReceptenIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recepten/$slug': {
      id: '/_layout/recepten/$slug'
      path: '/recepten/$slug'
      fullPath: '/recepten/$slug'
      preLoaderRoute: typeof LayoutReceptenSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBehandelingenRoute: typeof LayoutBehandelingenRoute
  LayoutBloedsuikertrajectRoute: typeof LayoutBloedsuikertrajectRoute
  LayoutContactRoute: typeof LayoutContactRoute
  LayoutCookiePolicyRoute: typeof LayoutCookiePolicyRoute
  LayoutDarmtrajectRoute: typeof LayoutDarmtrajectRoute
  LayoutEBookRoute: typeof LayoutEBookRoute
  LayoutEBookBoodschappenlijstRoute: typeof LayoutEBookBoodschappenlijstRoute
  LayoutEBookMealprepSnacksRoute: typeof LayoutEBookMealprepSnacksRoute
  LayoutEBookReceptenSnacksRoute: typeof LayoutEBookReceptenSnacksRoute
  LayoutEBookWeekmenuRoute: typeof LayoutEBookWeekmenuRoute
  LayoutFaqRoute: typeof LayoutFaqRoute
  LayoutGlowupRoute: typeof LayoutGlowupRoute
  LayoutHormoontrajectRoute: typeof LayoutHormoontrajectRoute
  LayoutMethodRoute: typeof LayoutMethodRoute
  LayoutNieuwsbriefRoute: typeof LayoutNieuwsbriefRoute
  LayoutOverMijRoute: typeof LayoutOverMijRoute
  LayoutPodcastRoute: typeof LayoutPodcastRoute
  LayoutPrivacyRoute: typeof LayoutPrivacyRoute
  LayoutTermsRoute: typeof LayoutTermsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutBlogSlugRoute: typeof LayoutBlogSlugRoute
  LayoutReceptenSlugRoute: typeof LayoutReceptenSlugRoute
  LayoutBlogIndexRoute: typeof LayoutBlogIndexRoute
  LayoutReceptenIndexRoute: typeof LayoutReceptenIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBehandelingenRoute: LayoutBehandelingenRoute,
  LayoutBloedsuikertrajectRoute: LayoutBloedsuikertrajectRoute,
  LayoutContactRoute: LayoutContactRoute,
  LayoutCookiePolicyRoute: LayoutCookiePolicyRoute,
  LayoutDarmtrajectRoute: LayoutDarmtrajectRoute,
  LayoutEBookRoute: LayoutEBookRoute,
  LayoutEBookBoodschappenlijstRoute: LayoutEBookBoodschappenlijstRoute,
  LayoutEBookMealprepSnacksRoute: LayoutEBookMealprepSnacksRoute,
  LayoutEBookReceptenSnacksRoute: LayoutEBookReceptenSnacksRoute,
  LayoutEBookWeekmenuRoute: LayoutEBookWeekmenuRoute,
  LayoutFaqRoute: LayoutFaqRoute,
  LayoutGlowupRoute: LayoutGlowupRoute,
  LayoutHormoontrajectRoute: LayoutHormoontrajectRoute,
  LayoutMethodRoute: LayoutMethodRoute,
  LayoutNieuwsbriefRoute: LayoutNieuwsbriefRoute,
  LayoutOverMijRoute: LayoutOverMijRoute,
  LayoutPodcastRoute: LayoutPodcastRoute,
  LayoutPrivacyRoute: LayoutPrivacyRoute,
  LayoutTermsRoute: LayoutTermsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutBlogSlugRoute: LayoutBlogSlugRoute,
  LayoutReceptenSlugRoute: LayoutReceptenSlugRoute,
  LayoutBlogIndexRoute: LayoutBlogIndexRoute,
  LayoutReceptenIndexRoute: LayoutReceptenIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  DarmtherapieTrajectRoute: DarmtherapieTrajectRoute,
  LinktreeRoute: LinktreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
